### ISSUE TITLE
Required modules return the same objects?

### ISSUE THREAD

**Issue by GCheung55** [sebmarkbage/link.js#2]
Hey Sebastian, I'm getting this weird behavior where the output from modules that are exporting the same things, when I think they shouldn't be.

https://gist.github.com/c7417b9b6345fcda7652

test.js is modifying the Neuro object literal with

``` javascript
Neuro.test = true;
```

Neuro.js hasn't been modified.

Doing `require: 'test', 'libs/Neuro/Neuro';` should return two different objects, right?

**Comment by sebmarkbage** [comment]
That is expected. It works the same with all the modern loaders. Any module is executed exactly once and the exported values are cached for future requires.

**Comment by GCheung55** [comment]
@calyptus thanks for clarifying. I appreciate it.
